version: "3.2"

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268

  one:
    image: zhenik/one
    build: ./one
    ports:
      - 8081:8080
    environment:
      JAEGER_SERVICE_NAME: jaeger
  two:
    image: zhenik/two
    build: ./two
    ports:
      - 8082:8080

#  spring:
#    image: demo/spring:jaeger
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      JAEGER_SERVICE_NAME: spring
#      JAEGER_AGENT_HOST: jaeger
#      JAEGER_SAMPLER_TYPE: const
#      JAEGER_SAMPLER_PARAM: 1
#      JAEGER_REPORTER_MAX_QUEUE_SIZE: 10000