version: "3.2"

services:

#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - 5775:5775/udp
#      - 6831:6831/udp
#      - 6832:6832/udp
#      - 5778:5778
#      - 16686:16686
#      - 14268:14268

  tracing-jaeger-collector:
    image: jaegertracing/jaeger-collector:1.1.0
    command: [
      "/go/bin/collector-linux",
      "--span-storage.type=cassandra",
      "--cassandra.keyspace=jaeger_v1_dc1",
      "--cassandra.servers=tracing-jaeger-cassandra"]
    depends_on:
      - tracing-jaeger-cassandra
      - tracing-jaeger-cassandra-schema

  tracing-jaeger-query:
    image: jaegertracing/jaeger-query:1.1.0
    command: [
      "/go/bin/query-linux",
      "--span-storage.type=cassandra",
      "--cassandra.keyspace=jaeger_v1_dc1",
      "--cassandra.servers=tracing-jaeger-cassandra",
      "--query.static-files=/go/jaeger-ui/"]
    ports:
      - 16686:16686
      - 16687
    depends_on:
      - tracing-jaeger-cassandra
      - tracing-jaeger-cassandra-schema

  tracing-jaeger-agent:
    image: jaegertracing/jaeger-agent:1.1.0
    command: [
      "/go/bin/agent-linux",
      "--collector.host-port=tracing-jaeger-collector:14267"]
    ports:
      - 6831:6831/udp
    depends_on:
      - tracing-jaeger-collector

  tracing-jaeger-cassandra:
    image: cassandra:3.9
    ports:
      - 9042:9042

  tracing-jaeger-cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.1.0
    environment:
      - CQLSH_HOST=tracing-jaeger-cassandra
    depends_on:
      - tracing-jaeger-cassandra

  one:
    image: zhenik/one
    build: ./one
    ports:
      - 11111:11111
    network_mode: host
    environment:
      - JAEGER_AGENT_HOST = tracing-jaeger-agent
      - JAEGER_AGENT_PORT = 6831

  two:
    image: zhenik/two
    build: ./two
    ports:
      - 22222:22222
#    network_mode: host
    environment:
      - JAEGER_AGENT_HOST = tracing-jaeger-agent
      - JAEGER_AGENT_PORT = 6831